import { deriveSource, worstSource, type Provenance, type QuoteSource } from '@shared/provenance.ts'

import type { LiveQuote } from '@/lib/stores/quote-store'

/**
 * Turning what is in the store into what the UI may claim.
 *
 * Everything here derives on render and nothing is stored. `quotes` has no
 * `source` column on purpose: freshness is a function of the current time, so a
 * row written as LIVE is stale minutes later with no write to invalidate it.
 */

/** How often the shared clock advances. */
export const PROVENANCE_HEARTBEAT_MS = 30_000

/**
 * The provenance of one figure on screen.
 *
 * `isInterpolated` is derived, never stored: a figure is synthetic exactly when
 * the tween has not yet arrived at the anchor.
 */
export function provenanceOf(quote: LiveQuote, now: Date): Provenance {
  return {
    source: deriveSource(quote.provider, quote.providerTs, now),
    provider: quote.provider,
    providerTs: quote.providerTs,
    fetchedAt: quote.fetchedAt,
    isInterpolated: quote.ltp !== quote.anchor,
  }
}

/**
 * What the shell badge reports: the worst provenance among the prices actually
 * on screen.
 *
 * **Symbols with no price are excluded, and that is a deliberate reading of
 * "on screen".** `worstSource([])` answers STALE — the honest pessimistic answer
 * when there is nothing to vouch for — so folding in the symbols that render an
 * em dash would pin the badge to STALE on account of *absent* data and say
 * nothing about the figures the visitor can actually see. A row showing an em
 * dash makes no claim and therefore cannot be dishonest.
 *
 * Null when nothing is priced at all: with no price on screen there is no claim
 * to characterise, and the badge renders nothing rather than inventing a verdict.
 */
export function badgeSource(quotes: Record<string, LiveQuote>, now: Date): QuoteSource | null {
  const priced = Object.values(quotes).filter((quote) => Number.isFinite(quote.anchor))
  if (priced.length === 0) return null
  return worstSource(priced.map((quote) => deriveSource(quote.provider, quote.providerTs, now)))
}

/** What the badge's explanation says, and what the price announces to a screen reader. */
export const SOURCE_COPY: Record<QuoteSource, { label: string; meaning: string }> = {
  LIVE: {
    label: 'Live',
    meaning: 'Streamed from the exchange as it trades.',
  },
  DELAYED: {
    label: 'Delayed',
    meaning:
      'Polled from a public endpoint, so it lags the exchange. It is a real traded price, just not the current one.',
  },
  STALE: {
    label: 'Stale',
    meaning:
      'Nothing fresh has arrived for this price. Treat the figure as out of date rather than current.',
  },
  SIMULATED: {
    label: 'Simulated',
    meaning:
      'Generated by this project, not observed on any exchange. It walks from a real previous close but no trade happened at this number.',
  },
}
