import {
  deriveSource,
  worstSource,
  type Provenance,
  type QuoteProviderName,
  type QuoteSource,
} from '@shared/provenance.ts'

import type { LiveQuote } from '@/lib/stores/quote-store'

/**
 * Turning what is in the store into what the UI may claim.
 *
 * Everything here derives on render and nothing is stored. `quotes` has no
 * `source` column on purpose: freshness is a function of the current time, so a
 * row written as LIVE is stale minutes later with no write to invalidate it.
 */

/** How often the shared clock advances. */
export const PROVENANCE_HEARTBEAT_MS = 30_000

/**
 * The provenance of one figure on screen.
 *
 * `isInterpolated` is derived, never stored: a figure is synthetic exactly when
 * the tween has not yet arrived at the anchor.
 */
export function provenanceOf(quote: LiveQuote, now: Date): Provenance {
  return {
    source: deriveSource(quote.provider, quote.providerTs, now),
    provider: quote.provider,
    providerTs: quote.providerTs,
    fetchedAt: quote.fetchedAt,
    isInterpolated: quote.ltp !== quote.anchor,
  }
}

/**
 * What the shell badge reports: the worst provenance among the prices actually
 * on screen.
 *
 * **Symbols with no price are excluded, and that is a deliberate reading of
 * "on screen".** `worstSource([])` answers STALE — the honest pessimistic answer
 * when there is nothing to vouch for — so folding in the symbols that render an
 * em dash would pin the badge to STALE on account of *absent* data and say
 * nothing about the figures the visitor can actually see. A row showing an em
 * dash makes no claim and therefore cannot be dishonest.
 *
 * Null when nothing is priced at all: with no price on screen there is no claim
 * to characterise, and the badge renders nothing rather than inventing a verdict.
 */
export function badgeSource(quotes: Record<string, LiveQuote>, now: Date): QuoteSource | null {
  const priced = Object.values(quotes).filter((quote) => Number.isFinite(quote.anchor))
  if (priced.length === 0) return null
  return worstSource(priced.map((quote) => deriveSource(quote.provider, quote.providerTs, now)))
}

/** What the badge's explanation says, and what the price announces to a screen reader. */
export const SOURCE_COPY: Record<QuoteSource, { label: string; meaning: string }> = {
  LIVE: {
    label: 'Live',
    meaning: 'Streamed from the exchange as it trades.',
  },
  DELAYED: {
    label: 'Delayed',
    meaning:
      'Polled from a public endpoint, so it lags the exchange. It is a real traded price, just not the current one.',
  },
  STALE: {
    label: 'Stale',
    meaning:
      'Nothing fresh has arrived for this price. Treat the figure as out of date rather than current.',
  },
  SIMULATED: {
    label: 'Simulated',
    meaning:
      'Generated by this project, not observed on any exchange. It walks from a real previous close but no trade happened at this number.',
  },
}

/**
 * The index strip's provenance, derived pessimistically.
 *
 * The composite is an average over many symbols, so there is no single
 * `provider`/`providerTs` pair to derive from. `market_composite` therefore
 * returns the raw inputs — every distinct provider among the constituents, and
 * the oldest timestamp any of them reported — and this pairs each provider with
 * that oldest timestamp before taking the worst answer.
 *
 * **That pairing is deliberately harsher than reality.** A provider whose own
 * row is fresh may be assessed against another's older stamp, so the strip can
 * under-claim its freshness but never over-claim it. A claim about data quality
 * may only ever err downwards.
 *
 * The pairing is sound because of the schema invariant that every non-`SIMULATOR`
 * row carries a non-null `provider_ts`: the only provider that can contribute a
 * null is `SIMULATOR`, and `deriveSource` answers `SIMULATED` for it regardless
 * of any timestamp.
 *
 * Null when nothing is priced. With no constituents there is no claim to
 * characterise, and the strip renders an em dash rather than inventing a verdict
 * — the same call `badgeSource` makes.
 */
export function compositeSource(
  providers: readonly QuoteProviderName[],
  oldestProviderTs: Date | null,
  now: Date
): QuoteSource | null {
  if (providers.length === 0) return null
  return worstSource(providers.map((provider) => deriveSource(provider, oldestProviderTs, now)))
}

/**
 * Provenance for a row that has not entered the live store yet.
 *
 * **Without this, a server-rendered price has no provenance and therefore no
 * price.** `PriceWithProvenance` renders an em dash whenever provenance is null
 * — correctly, since a figure with nothing behind it must not be shown — so a
 * surface that passed `live ? provenanceOf(live, now) : null` rendered every
 * price as an em dash on the server and on the first client render, while the
 * change column beside it displayed the server's own figure. A row claiming a
 * 25% move with no price is worse than either half alone. Found at the Phase 3
 * checkpoint, in the SSR HTML.
 *
 * `isInterpolated` is false by construction: nothing has tweened yet.
 *
 * Null when the row carries no price, no provider or no fetch time — there is
 * nothing to vouch for, and the em dash is then the honest render.
 */
export function serverProvenance(
  row: {
    ltp: number | null
    provider: QuoteProviderName | null
    providerTs: string | null
    fetchedAt: string | null
  },
  now: Date
): Provenance | null {
  if (row.ltp === null || row.provider === null || row.fetchedAt === null) return null

  const providerTs = row.providerTs === null ? null : new Date(row.providerTs)

  return {
    source: deriveSource(row.provider, providerTs, now),
    provider: row.provider,
    providerTs,
    fetchedAt: new Date(row.fetchedAt),
    isInterpolated: false,
  }
}
