import Link from 'next/link'

type Clause = {
  heading: string
  body: string
}

const CLAUSES: readonly Clause[] = [
  {
    heading: 'Not affiliated with Zerodha',
    body: 'This is an independent portfolio project built to study how a trading terminal works. It is not affiliated with, endorsed by, sponsored by, or connected to Zerodha Broking Ltd. or any of its subsidiaries. Zerodha and Kite are their trademarks, used here only to say plainly what this project was modelled on. No branding, logo, or copy has been reproduced from their site.',
  },
  {
    heading: 'No real trading happens here',
    body: 'There is no brokerage account behind this application, no exchange connectivity, no order routing, and no payment integration of any kind. Nothing you do here reaches a market. The cash balance is a number in a database row, created when you sign in and resettable whenever you like, and it can never be deposited or withdrawn because there is nothing to deposit or withdraw.',
  },
  {
    heading: 'Nothing here is financial advice',
    body: 'This project is not a registered investment adviser, research analyst, or broker, and nothing in it is a recommendation to buy or sell anything. Profits made in the simulator carry no information about what would have happened with real money, in either direction — the mechanics are faithful, but the psychology of risking your own capital is the part a simulator cannot reproduce.',
  },
  {
    heading: 'Where the price data comes from',
    body: 'Prices are fetched from third-party market data providers on a schedule and may be delayed, incomplete, or — when every provider is unreachable — generated by a simulator seeded from the last real price. Every price on screen carries its own provenance, so you can always tell which of those you are looking at. Nothing here is an official quotation, and the data is not licensed for redistribution.',
  },
  {
    heading: 'No warranty, and no guarantee it stays up',
    body: 'This runs on free infrastructure that sleeps when idle and can be taken down at any time. It is provided as-is, without warranty of any kind. Data may be lost. Features may change or disappear. Do not rely on it for anything that matters.',
  },
]

export function LegalDisclaimer() {
  return (
    <section className="py-section">
      <div className="mx-auto max-w-7xl px-4 md:px-6">
        <div className="max-w-prose">
          <h1 className="text-display font-bold text-ink">Disclaimer</h1>
          <p className="mt-6 text-body">
            The short version: none of this is real, none of it is advice, and it has nothing to do
            with Zerodha. The longer version follows, and the specific ways this simulator behaves
            differently from a real broker are set out{' '}
            <Link
              href="#simplifications"
              className="text-brand underline underline-offset-4 light:text-ink"
            >
              further down
            </Link>
            .
          </p>
        </div>

        <dl className="mt-10 flex max-w-prose flex-col gap-8">
          {CLAUSES.map((clause) => (
            <div key={clause.heading}>
              <dt className="text-title-sm font-semibold text-ink">{clause.heading}</dt>
              <dd className="mt-2 text-body-sm text-body">{clause.body}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  )
}
